// Implementation of the wasmtime-generated `host::Host` trait on `HostState`.
// This is the sole WASM↔core bridge. Mode dispatch (live vs
// replay) is done inside each method by matching `self.mode`.
//
// The trait is generated by `wasmtime::component::bindgen!` from
// `wit/loom-surface.wit::interface host`. The generated types are in
// `crate::wit_type_marshaller::loom_surface_bindings::loom::surface::`.
//
// NOTE: Return types mirror WIT definitions exactly (no wasmtime::Result
// wrapper). Methods that cannot propagate errors (clock_now, rng_next_u64)
// panic on internal failure — this produces a guest trap.
//
// wasmtime 44: `async: true` was removed from bindgen!; imports now use
// RPITIT (`impl Future + Send`). #[async_trait] is incompatible with the
// generated trait. Each method does its sync work up-front and returns a
// single `async move { ... }` block to avoid heterogeneous return types.

use super::host_function_table::HostState;
use crate::host_function_table::net_guard::do_http_request;
use crate::wit_type_marshaller::loom_surface_bindings::loom::surface::{
    host::Host,
    types::{
        ContentRef, EvaluateResult, HostError, Instant, LogLevel, NavigateResult, NetReq, NetResp,
        Receipt, SetInputFilesResult, WaitResult,
    },
};
use crate::wit_type_marshaller::Mode;
use loom_core::content_store::ContentRef as CoreContentRef;
use loom_core::vault::NetRequest;
use loom_shared::error_format::LoomErrorCode;
use std::sync::Arc;

// Convert WIT ContentRef → loom-core ContentRef
fn wit_ref_to_core(r: ContentRef) -> CoreContentRef {
    CoreContentRef {
        sha256: r.sha256,
        size_bytes: r.size,
    }
}

// Convert loom-core ContentRef → WIT ContentRef
pub(crate) fn core_ref_to_wit(r: CoreContentRef) -> ContentRef {
    ContentRef {
        sha256: r.sha256,
        size: r.size_bytes,
    }
}

/// Resolve THIS navigation's main-document event from the shim's
/// attribution index. `navigate_execute`'s failure verdict (HTTP 4xx/5xx,
/// transport error) is scoped to this single event — an iframe's document
/// error or a stale prior-load event must never fail the whole navigate
/// (those events stay in `network_events` for observability). `None`
/// (no events, only iframe documents, or a legacy pre-field shim payload)
/// means no typed navigate failure is raised.
pub(super) fn main_document_event(
    events: &[loom_shared::navigate_outcome::LoomNetworkEvent],
    main_document_event_index: Option<u32>,
) -> Option<&loom_shared::navigate_outcome::LoomNetworkEvent> {
    main_document_event_index.and_then(|i| events.get(i as usize))
}

// Convert a LoomError → WIT HostError (generated, string payload)
pub(crate) fn loom_to_wit_error(err: loom_shared::error_format::LoomError) -> HostError {
    let msg = err.message.clone();
    match err.code {
        LoomErrorCode::BudgetExceeded | LoomErrorCode::BudgetRateLimited => {
            HostError::BudgetExceeded(msg)
        }
        LoomErrorCode::VaultRejection
        | LoomErrorCode::VaultGrantExpired
        | LoomErrorCode::VaultGrantRevoked
        | LoomErrorCode::VaultUnknownLabel => HostError::VaultRejection(msg),
        LoomErrorCode::ShimFailure
        | LoomErrorCode::ShimTimeout
        | LoomErrorCode::ShimBreakerOpen => HostError::ShimFailure(msg),
        LoomErrorCode::StoreIntegrityFailed => HostError::StoreIntegrityFailed(msg),
        _ => HostError::Internal(msg),
    }
}

/// True when an opaque `shim_call` CBOR payload is a `Network.getCookies`
/// request. `web.get_cookies` is the only verb that emits this method, so it
/// is a precise tag for the cookie-surfacing capture below. A decode miss
/// returns `false` (the capture simply doesn't run — the receipt is unchanged).
fn is_get_cookies_request(msg: &[u8]) -> bool {
    loom_shared::shim_protocol::ciborium_from_slice::<loom_shared::shim_protocol::CdpMessage>(msg)
        .map(|m| m.method == "Network.getCookies")
        .unwrap_or(false)
}

/// Decode the `Network.getCookies` CDP response payload (re-encoded CBOR of the
/// CDP result `{cookies: [...]}`) into a canonical-JSON cookie ARRAY string.
/// Returns `None` if the bytes don't decode or carry no `cookies` array, so the
/// caller can fall through to the prior behaviour (no `get_cookies_result`).
///
/// The WASM guest can't do this (it ships without a CBOR decoder by design), so
/// the host owns the decode and hands the array to `SessionExecutor` for the
/// receipt. Values are kept RAW here (operator-facing receipts include them per
/// D7); value redaction for the replay hash chain happens later in
/// `assemble_cookies_canonical_bytes`.
fn decode_get_cookies_array(payload_cbor: &[u8]) -> Option<String> {
    let v: serde_json::Value = ciborium::de::from_reader(payload_cbor).ok()?;
    let cookies = v.get("cookies")?;
    if !cookies.is_array() {
        return None;
    }
    serde_json::to_string(cookies).ok()
}

impl HostState {
    /// Deterministic per-session virtual clock (ms) for receipt timestamps when
    /// determinism is enabled; `None` falls back to the harness clock. A pure
    /// function of the per-session `action_id` — no shared mutable state — so two
    /// independent same-seed runs produce byte-equal timestamps and concurrent
    /// sessions cannot bleed clock state into each other (the manifest-chain
    /// cross-run determinism property; see decisions D9).
    pub(crate) fn deterministic_clock_ms(&self) -> Option<u64> {
        if self.mode == Mode::Live && !self.no_determinism {
            Some(
                self.action_id
                    .saturating_mul(loom_core::determinism_harness::DETERMINISTIC_ACTION_DELTA_MS),
            )
        } else {
            None
        }
    }
}

impl Host for HostState {
    // --- Determinism sources ---

    fn clock_now(&mut self) -> impl ::core::future::Future<Output = Instant> + Send {
        let ms = match self.mode {
            Mode::Live => self
                .deterministic_clock_ms()
                .unwrap_or_else(|| self.determinism.clock_now()),
            Mode::Replay => {
                let table = self
                    .replay_table
                    .as_ref()
                    .expect("replay_table not set in replay mode");
                table.pop_clock().expect("replay clock underflow")
            }
        };
        async move { Instant { epoch_ms: ms } }
    }

    fn rng_next_u64(&mut self) -> impl ::core::future::Future<Output = u64> + Send {
        let val = match self.mode {
            Mode::Live => self.determinism.rng_next(),
            Mode::Replay => {
                let table = self
                    .replay_table
                    .as_ref()
                    .expect("replay_table not set in replay mode");
                table.pop_rng().expect("replay rng underflow")
            }
        };
        async move { val }
    }

    // --- Content store ---

    fn blob_put(
        &mut self,
        bytes: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<ContentRef, HostError>> + Send {
        let result = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "blob_put not allowed in replay mode".to_owned(),
            ))
        } else {
            match self.core.content_store.put(&bytes) {
                Ok(r) => Ok(core_ref_to_wit(r)),
                Err(e) => Err(loom_to_wit_error(e)),
            }
        };
        async move { result }
    }

    fn blob_get(
        &mut self,
        r: ContentRef,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        let result = match self.core.content_store.get(&wit_ref_to_core(r)) {
            Ok(bytes) => Ok(bytes),
            Err(e) => Err(loom_to_wit_error(e)),
        };
        async move { result }
    }

    fn record_screenshot(
        &mut self,
        cdp_response: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<ContentRef, HostError>> + Send {
        // Decode the CDP `{data: <base64-PNG>}` envelope into raw PNG bytes so
        // the content store holds a renderable image and the returned hash
        // resolves to an actual `image/png`.
        let result = match loom_shared::screenshot_decode::decode_cdp_screenshot(&cdp_response) {
            Ok(png) if !loom_shared::screenshot_decode::is_png(&png) => {
                // Decoded to something that isn't a PNG (empty/truncated/garbage).
                // Refuse to store it — a 0-byte or non-image blob would only
                // produce a dangling, unrenderable screenshot_after_hash.
                Err(HostError::ShimFailure(
                    "{\"kind\":\"screenshot_decode_failed\",\"reason\":\"decoded bytes are not a PNG\"}"
                        .to_string(),
                ))
            }
            Ok(png) => {
                if self.mode == Mode::Replay {
                    // Replay must NOT write to the content store, but must return
                    // the SAME hash live mode stored so the receipt's
                    // screenshot_after_hash is byte-identical. Derive it from the
                    // decoded bytes (the blob already exists in CAS from live).
                    Ok(ContentRef {
                        sha256: loom_core::content_store::sha256_hex(&png),
                        size: png.len() as u64,
                    })
                } else {
                    match self.core.content_store.put(&png) {
                        Ok(r) => Ok(core_ref_to_wit(r)),
                        Err(e) => Err(loom_to_wit_error(e)),
                    }
                }
            }
            Err(e) => Err(HostError::ShimFailure(format!(
                "{{\"kind\":\"screenshot_decode_failed\",\"reason\":\"{e}\"}}"
            ))),
        };
        async move { result }
    }

    // --- Network (vault-mediated; HARD invariant) ---

    fn net_request(
        &mut self,
        req: NetReq,
    ) -> impl ::core::future::Future<Output = Result<NetResp, HostError>> + Send {
        // Do all sync work (incl. vault substitution) before the async block so
        // the returned future holds only Send types and does not borrow self.
        let maybe_core_req: Result<NetRequest, HostError> = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "net_request not allowed in replay mode".to_owned(),
            ))
        } else {
            let mut core_req = NetRequest {
                url: req.url.clone(),
                method: req.method.clone(),
                headers: req.headers.iter().cloned().collect(),
                authorization: None,
                body: req.body.clone(),
                origin: req.url.clone(),
                scopes: Vec::new(),
            };
            // Vault credential substitution (grant_id "default" for now).
            // The dispatching session scopes the grant lookup (NFR-DET-01:
            // grant ids are deterministic per session).
            let _ = self.core.vault.substitute(
                &self.session_id,
                loom_core::vault::GrantId("default".to_owned()),
                &mut core_req,
            );
            Ok(core_req)
        };

        async move {
            let core_req = maybe_core_req?;
            // Perform the actual HTTP request via reqwest
            let resp = do_http_request(core_req)
                .await
                .map_err(HostError::Internal)?;

            // HARD invariant: strip Authorization from response headers
            let headers: Vec<(String, String)> = resp
                .headers
                .iter()
                .filter(|(k, _)| k.to_lowercase() != "authorization")
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();

            Ok(NetResp {
                status: resp.status,
                headers,
                body: resp.body,
            })
        }
    }

    // --- Vault (v0.9.6 web-cookie-injection grant resolution) ---

    fn vault_substitute_cookies(
        &mut self,
        grant_id: String,
        session_id: String,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        use loom_core::manifest_writer::manifest_writer::SessionId;
        use loom_core::vault::GrantId;
        // Replay mode: refuse. Cookie values in replay must be supplied
        // externally via `replay_cookie_values` (§5), not pulled from the
        // live vault. This keeps replay self-contained.
        let result = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "vault_substitute_cookies not allowed in replay mode".to_owned(),
            ))
        } else {
            match self
                .core
                .vault
                .substitute_cookies(GrantId(grant_id), SessionId(session_id))
            {
                // Zeroizing<Vec<u8>> → Vec<u8>. The original Zeroizing
                // wrapper drops here, wiping its backing buffer (per the
                // v0.9.5 contract that raw cookie values are wiped in
                // daemon memory). The non-zeroizing copy below crosses
                // the WIT boundary into the WASM guest. The proper
                // through-boundary heap-wipe path is the §10 hardening
                // (separate tier).
                Ok(zeroized) => Ok(zeroized.to_vec()),
                Err(e) => Err(loom_to_wit_error(e)),
            }
        };
        async move { result }
    }

    // --- Out-of-process shim bridge ---

    fn shim_call(
        &mut self,
        shim_id: String,
        msg: Vec<u8>,
    ) -> impl ::core::future::Future<Output = Result<Vec<u8>, HostError>> + Send {
        use crate::shim_manager::ShimId;
        // Namespace the shim id by the active session so each session
        // gets its own subprocess (reuse falls out: same
        // session_id → same effective ShimId → cached ShimProcess).
        let session_id = self.session_id.0.clone();
        let effective_id = ShimId(format!("{}:{}", shim_id, session_id));
        let shim_manager = self.shim_manager.clone();
        let session_id_for_register = session_id.clone();
        let raw_shim_id_for_register = shim_id.clone();
        // Capture profile + downloads_dir for env-var
        // injection at lazy-register time. Cloned out of `&mut self` so
        // the async block can move them.
        let profile_for_register = self.profile.clone();
        let downloads_dir_for_register = self.downloads_dir.clone();
        // web.get_cookies surfacing: tag the request now (cheap, off the async
        // block) and clone the side-channel handle so the async block can stash
        // the decoded cookie array once the shim responds. SessionExecutor reads
        // it after the guest returns.
        let is_get_cookies = is_get_cookies_request(&msg);
        let cookie_capture = self.cookie_capture.clone();

        let maybe_call: Result<
            (ShimId, Vec<u8>, Arc<crate::shim_manager::ShimManager>),
            HostError,
        > = if self.mode == Mode::Replay {
            Err(HostError::Internal(
                "shim_call not allowed in replay mode".to_owned(),
            ))
        } else {
            Ok((effective_id.clone(), msg, shim_manager))
        };

        async move {
            match maybe_call {
                Err(e) => Err(e),
                Ok((effective_id, msg, shim_manager)) => {
                    // Lazy-register on first call. The daemon (L12) is
                    // expected to provide a template ShimConfig at
                    // construction time keyed by the bare shim name
                    // (e.g. "chromium"); we clone-and-namespace it here.
                    if !shim_manager.is_registered(&effective_id) {
                        if let Some(template) = shim_manager
                            .configs
                            .get(&ShimId(raw_shim_id_for_register.clone()))
                            .map(|c| c.clone())
                        {
                            let mut config = template;
                            // Per-session user-data-dir override.
                            let dir = std::env::temp_dir()
                                .join(format!("loom-chromium-{}", session_id_for_register));
                            config.env.push((
                                "LOOM_SHIM_USER_DATA_DIR".into(),
                                dir.display().to_string(),
                            ));
                            // Inject profile + downloads_dir env vars so the
                            // shim's CDP bootstrap can send
                            // `Browser.setDownloadBehavior(allowAndName,
                            // downloadPath=<dir>)` at startup. Confines
                            // Chromium downloads to the session-scoped dir.
                            if profile_for_register == "safe" {
                                config.env.push(("LOOM_SHIM_PROFILE".into(), "safe".into()));
                                match &downloads_dir_for_register {
                                    Some(d) => {
                                        config.env.push((
                                            "LOOM_SHIM_DOWNLOADS_DIR".into(),
                                            d.display().to_string(),
                                        ));
                                    }
                                    None => {
                                        // INVARIANT VIOLATION (mirror of the
                                        // navigate_execute path below) —
                                        // safe profile sessions must always
                                        // have downloads_dir per
                                        // LocalSessionManager::create.
                                        tracing::error!(
                                            session_id = %session_id_for_register,
                                            "safe-profile invariant: safe profile session has no \
                                             downloads_dir; Chromium download confinement DISABLED \
                                             for this shim"
                                        );
                                    }
                                }
                            }
                            shim_manager.register(effective_id.clone(), config);
                        } else {
                            return Err(HostError::ShimFailure(format!(
                                "no template config registered for shim {raw_shim_id_for_register}"
                            )));
                        }
                    }
                    match shim_manager.send(effective_id, msg).await {
                        Ok(bytes) => {
                            // Decode + stash the cookie array for the receipt.
                            // Best-effort: a decode miss leaves the receipt as
                            // before (outcome_hash still rides the response bytes).
                            if is_get_cookies {
                                if let Some(json) = decode_get_cookies_array(&bytes) {
                                    *cookie_capture.lock() = Some(json);
                                }
                            }
                            Ok(bytes)
                        }
                        Err(e) => Err(loom_to_wit_error(e)),
                    }
                }
            }
        }
    }

    // capture-policy=fingerprint: post-action DOM fingerprint for DOM-mutating
    // selector interactions. Returns Some(sha256-hex of the normalized
    // DOM.getDocument response) ONLY under the fingerprint tier; None otherwise.
    // The shim already normalizes DOM.getDocument (frameId-stripped) via
    // `normalize_dom_cbor`, so the hash is content-bearing + cross-run-stable —
    // the SAME bytes `web.snapshot` hashes. Best-effort (D6): an encode/send error
    // omits the field + warns; it never fails the interaction. Record-only:
    // returns None in replay (the shim is not driven there).
    fn capture_dom_after_hash(
        &mut self,
    ) -> impl ::core::future::Future<Output = Result<Option<String>, HostError>> + Send {
        use crate::shim_manager::ShimId;
        use loom_shared::shim_protocol::{ciborium_to_vec, CdpMessage};

        // Gate up-front (off the async block): replay never drives the shim, and a
        // non-fingerprint session must pay NO extra DOM.getDocument round-trip.
        let gated_off = self.mode == Mode::Replay || !self.capture_dom_after;
        let session_id = self.session_id.0.clone();
        let shim_manager = self.shim_manager.clone();

        async move {
            if gated_off {
                return Ok(None);
            }
            // Same effective shim id as `shim_call` ("chromium:<session>"); the
            // interaction's own shim_call already lazy-registered + spawned it.
            let effective_id = ShimId(format!("chromium:{session_id}"));
            // depth:-1, pierce:true — identical envelope to navigate STEP 5 /
            // web.snapshot, so the shim's cdp_send normalize seam fires.
            let dom_msg = CdpMessage {
                method: "DOM.getDocument".to_string(),
                params: ciborium::value::Value::Map(vec![
                    (
                        ciborium::value::Value::Text("depth".to_string()),
                        ciborium::value::Value::Integer((-1i64).into()),
                    ),
                    (
                        ciborium::value::Value::Text("pierce".to_string()),
                        ciborium::value::Value::Bool(true),
                    ),
                ]),
            };
            let bytes = match ciborium_to_vec(&dom_msg) {
                Ok(b) => b,
                Err(e) => {
                    tracing::warn!(
                        session_id = %session_id,
                        error = %e,
                        "capture_dom_after_hash: encode DOM.getDocument failed; omitting dom_after_hash"
                    );
                    return Ok(None);
                }
            };
            // Best-effort: a send failure (shim wedged / timeout / not registered)
            // omits the fingerprint rather than failing the interaction.
            match shim_manager.send(effective_id, bytes).await {
                Ok(resp) => {
                    // Reuse the canonical sha256 helper (same one navigate/snapshot
                    // hashing rides). `resp` is the shim-normalized DOM.getDocument
                    // response (frameId stripped) → content-stable across runs.
                    Ok(Some(loom_core::content_store::sha256_hex(&resp)))
                }
                Err(e) => {
                    tracing::warn!(
                        session_id = %session_id,
                        error = %e,
                        "capture_dom_after_hash: DOM.getDocument send failed; omitting dom_after_hash (best-effort)"
                    );
                    Ok(None)
                }
            }
        }
    }

    // --- Logging and receipts (side-effect free from host perspective) ---

    fn log_emit(
        &mut self,
        level: LogLevel,
        msg: String,
        fields: Vec<(String, String)>,
    ) -> impl ::core::future::Future<Output = ()> + Send {
        let _ = (level, msg, fields);
        // Route through HostObservability in the full implementation.
        async move {}
    }

    fn receipt_emit(&mut self, r: Receipt) -> impl ::core::future::Future<Output = ()> + Send {
        let _ = r;
        // receipt_emit is a no-op for now: navigate receipt fields are
        // returned directly from navigate_execute. Surface-driven
        // receipt emission lands in a follow-up.
        async move {}
    }

    // --- Typed navigate-execute host function ---

    /// See [`HostState::navigate_execute_impl`].
    fn navigate_execute(
        &mut self,
        action_id: String,
        url: String,
        until: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<NavigateResult, HostError>> + Send {
        self.navigate_execute_impl(action_id, url, until, budget_ms)
    }

    /// See [`HostState::wait_for_execute_impl`].
    fn wait_for_execute(
        &mut self,
        action_id: String,
        until: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<WaitResult, HostError>> + Send {
        self.wait_for_execute_impl(action_id, until, budget_ms)
    }

    // --- Typed evaluate-execute host function ---

    /// See [`HostState::evaluate_execute_impl`].
    fn evaluate_execute(
        &mut self,
        action_id: String,
        expression: String,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<EvaluateResult, HostError>> + Send {
        self.evaluate_execute_impl(action_id, expression, budget_ms)
    }

    /// See [`HostState::set_input_files_execute_impl`].
    fn set_input_files_execute(
        &mut self,
        action_id: String,
        payload: Vec<u8>,
        budget_ms: u64,
    ) -> impl ::core::future::Future<Output = Result<SetInputFilesResult, HostError>> + Send {
        self.set_input_files_execute_impl(action_id, payload, budget_ms)
    }
}

/// Convert a `ciborium::value::Value` (CDP `Runtime.evaluate.result.value`)
/// to a `serde_json::Value` suitable for canonical-JSON via `serde_jcs`.
///
/// Per  the wire bans IEEE-754 floats; numeric values
/// (integers and floats both) are emitted as canonical-JSON strings.
/// Non-representable CBOR (Bytes, Tag, non-string map keys) returns a
/// shaped `HostError::ShimFailure` so the caller surfaces a clean error
/// receipt rather than panicking the daemon (council Q8 policy).
pub(crate) fn cbor_value_to_json(
    v: ciborium::value::Value,
) -> Result<serde_json::Value, HostError> {
    use ciborium::value::Value;
    match v {
        Value::Null => Ok(serde_json::Value::Null),
        Value::Bool(b) => Ok(serde_json::Value::Bool(b)),
        Value::Integer(i) => Ok(serde_json::Value::String(format!("{}", i128::from(i)))),
        Value::Float(f) => {
            // numerics on the wire as strings. NaN /
            // Infinity / -Infinity round-trip as their literal IEEE-754
            // names; finite floats use Rust's default formatter (which
            // is round-trip-safe for f64).
            let s = if f.is_nan() {
                "NaN".to_string()
            } else if f.is_infinite() {
                if f.is_sign_negative() {
                    "-Infinity".to_string()
                } else {
                    "Infinity".to_string()
                }
            } else {
                format!("{f}")
            };
            Ok(serde_json::Value::String(s))
        }
        Value::Text(s) => Ok(serde_json::Value::String(s)),
        Value::Array(a) => {
            let mut out = Vec::with_capacity(a.len());
            for elem in a {
                out.push(cbor_value_to_json(elem)?);
            }
            Ok(serde_json::Value::Array(out))
        }
        Value::Map(m) => {
            // Q8: non-string keys → shaped error, not panic.
            let mut obj = serde_json::Map::with_capacity(m.len());
            for (k, val) in m {
                let key = match k {
                    Value::Text(s) => s,
                    _ => {
                        let detail = serde_json::json!({
                            "kind": "cbor_unrepresentable",
                            "reason": "non_string_map_key",
                        })
                        .to_string();
                        return Err(HostError::ShimFailure(detail));
                    }
                };
                obj.insert(key, cbor_value_to_json(val)?);
            }
            Ok(serde_json::Value::Object(obj))
        }
        Value::Bytes(_) => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "bytes",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
        Value::Tag(_, _) => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "tag",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
        _ => {
            let detail = serde_json::json!({
                "kind": "cbor_unrepresentable",
                "reason": "unknown_cbor_variant",
            })
            .to_string();
            Err(HostError::ShimFailure(detail))
        }
    }
}

// === SSRF guard (audit 2026-06-10: net_request is an unguarded SSRF
// primitive on the WIT trust boundary) ===
//
// `net_request` is a host primitive a (possibly compromised, per threat-model
// AB1) WASM guest can call directly from the daemon's network position. The
// guard below makes outbound HTTP from that primitive non-bypassable:
//
//   1. Scheme allowlist — only `http`/`https`.
//   2. DNS is resolved ONCE in the host (not by reqwest), every resolved
//      socket addr is checked against the blocked-range set, and the request
//      is pinned to those exact addrs via `resolve` so reqwest can never do a
//      second, unchecked lookup (the DNS-rebind window).
//   3. Auto-redirect is DISABLED; redirects are followed manually so the full
//      resolve+validate guard re-runs on every hop's `Location`.
//
// The blocked-range predicate lives in the pure, unit-tested
// `ip_is_blocked` / `validate_outbound_url` functions below.

#[cfg(test)]
mod cookie_capture_tests {
    use super::{decode_get_cookies_array, is_get_cookies_request};
    use ciborium::value::Value as Cbor;
    use loom_shared::shim_protocol::{ciborium_to_vec, CdpMessage};

    fn cdp_msg_bytes(method: &str) -> Vec<u8> {
        ciborium_to_vec(&CdpMessage {
            method: method.to_string(),
            params: Cbor::Map(vec![]),
        })
        .unwrap()
    }

    #[test]
    fn tags_get_cookies_requests_and_ignores_others() {
        assert!(is_get_cookies_request(&cdp_msg_bytes("Network.getCookies")));
        assert!(!is_get_cookies_request(&cdp_msg_bytes(
            "Network.setCookies"
        )));
        assert!(!is_get_cookies_request(&cdp_msg_bytes("Page.navigate")));
        // A non-CdpMessage payload must not panic and must read as "not cookies".
        assert!(!is_get_cookies_request(&[0xff, 0x00, 0x01]));
    }

    #[test]
    fn decodes_cookie_array_from_cdp_response_payload() {
        // Mirror a `Network.getCookies` CDP result `{cookies: [...]}` re-encoded
        // as CBOR exactly the way `ShimManager::send` hands it to the guest.
        let payload = Cbor::Map(vec![(
            Cbor::Text("cookies".into()),
            Cbor::Array(vec![Cbor::Map(vec![
                (Cbor::Text("name".into()), Cbor::Text("sid".into())),
                (Cbor::Text("value".into()), Cbor::Text("secret".into())),
                (Cbor::Text("domain".into()), Cbor::Text("x.com".into())),
                (Cbor::Text("httpOnly".into()), Cbor::Bool(true)),
            ])]),
        )]);
        let bytes = ciborium_to_vec(&payload).unwrap();
        let json = decode_get_cookies_array(&bytes).expect("decodes");
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(parsed.is_array());
        assert_eq!(parsed[0]["name"], "sid");
        assert_eq!(parsed[0]["value"], "secret"); // raw here; redaction happens in marshaller
        assert_eq!(parsed[0]["httpOnly"], true);
    }

    #[test]
    fn decode_returns_none_for_missing_or_non_array_cookies() {
        // No `cookies` key.
        let no_key = ciborium_to_vec(&Cbor::Map(vec![(
            Cbor::Text("foo".into()),
            Cbor::Text("bar".into()),
        )]))
        .unwrap();
        assert!(decode_get_cookies_array(&no_key).is_none());
        // `cookies` present but not an array.
        let not_array = ciborium_to_vec(&Cbor::Map(vec![(
            Cbor::Text("cookies".into()),
            Cbor::Text("oops".into()),
        )]))
        .unwrap();
        assert!(decode_get_cookies_array(&not_array).is_none());
        // Garbage bytes.
        assert!(decode_get_cookies_array(&[0xde, 0xad]).is_none());
    }
}
